--- !map:ActiveSupport::HashWithIndifferentAccess

"Notated music":
  label: records.notated_music
Libretto:
  label: records.libretto
Treatise:
  label: records.treatise
Mixed:
  label: records.mixed
Print:
  label: records.print
Composite:
  label: records.composite
Inventory:
  label: records.inventory
"rdau:P60191":
  label: relations.P60191
"rdau:P60198":
  label: relations.P60198
"rdau:P60311":
  label: relations.P60311
"rdau:P60312":
  label: relations.P60312
"rdau:P60195":
  label: relations.P60195
"rdau:P60242":
  label: relations.P60242
"rdau:P60274":
  label: relations.P60274
"rdau:P60194":
  label: relations.P60194
"rdau:P60183":
  label: relations.P60183