--- !map:ActiveSupport::HashWithIndifferentAccess

"Notated music":
  label: records.notated_music
Libretto:
  label: records.libretto
Treatise:
  label: records.treatise
Mixed:
  label: records.mixed
Print:
  label: records.print
Composite:
  label: records.composite