
:version:
  :name: tag_config
  :current: 2.0
  :authors: ["Chad Thatcher", "Sandra Tuppen", "Laurent Pugin", "Rodolfo Zitellini", "Stephan Hirsch"]


# NOTES FOR "tags" SECTION:
#
# The ":dependency:" field indicates a subtags reliance and function according to its parent.  Values are:
# false (no parent for this subtag.  Used for "a" or "" subtags or other subtags that are independant of other subtags)
# true  (must be in addition to parent subtag, cannot exist without it)
#
# Subtag ":occurrences:" fields are always within context of thier parent subtag.  In the case of parent sutags ("a", "" (blank)
# and some "w" tags) this defines the repetition attributes for the whole tag
#
# 0 (none. used only to keep tag/subtag configurations that are unused and therefore discarded on import)
# ? (none or one. this subtag need not be present, but at most only one occurance may exist)
# 1 (one occurance must exist. no more than one is allowed)
# + (one or more must exist.  at least one occurance must be present, more occurrences are allowed)
# * (none or more. none, one or many may exist)
#
# >where a tag or subtag is repeatable, there shouldn't be an upper limit on number of repeats allowed,
# >so I've amended all the values in the max_occur fields to "0".
# max_occur has now been removed entirely
#
# *DEPRECATED AND REMOVED* The "max_occur:" field is used in conjunction with the '+' or '*' ":occurrences:"
# field values to limit the number of occurrences to the specified maximum value.  A value of 0 inidicates
# and unlimited number of occurrences.  Only set this value to a positive number if it is absolutely
# necessary to set an upper limit on the number of occurrences of this subtag.
#
# >ST NOTE: TAGS 000 to 008
# >These are different from all the later tags in that they don't have any subtags (not even "a").
# >So should the master for each be changed to "" instead of a?
# This has now been corrected
#
# The ":export_as:" field specifies the mandatory value for a subtag on an export.  The subtag is only
# exported if both ":occurrences:" is set to "0" and this value is present.  This applies only to dependent
# subtags (i.e. not "a" subtags).
#
# "index" fields specify which marc fields are included in the fulltext ferret index when a record is
# inserted or updated in the masters table. See search_config.X.X.yml for more details on search functionality
# and the fulltext index.

:model: publication
:tags:
  "000":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "003":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "005":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "007":
    :master: ""
    :indicator: ""
    :occurrences: "*"
    :fields:
    - - ""
      - :no_browse: true
  "008":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "020":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "022":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "024":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "041":
    :master: a
    :indicator: ["0#", "1#"]
    :occurrences: "1"
    :fields:
    - - a
      - :occurrences: "*"
    - - d
      - :occurrences: "*"
    - - e
      - :occurrences: "*"
    - - g
      - :occurrences: "*"
        :no_browse: true
    - - h
      - :occurrences: "*"
  "044":
    :master: a
    :indicator: "##"
    :occurrences: "?"
    :fields:
    - - a
      - :occurrences: "?"
  "100":
    :master: "0"
    :indicator: "1#"
    :occurrences: "?"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Person
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: full_name
    - - d
      - :occurrences: "?"
        :browse_inline: true
        :foreign_class: ^0
        :foreign_field: life_dates
        :foreign_alternates: alternate_dates
    - - j
      - :occurrences: "?"
    - - "4"
      - :occurrences: "*"
        :browse_inline: true
  "210":
    :master: a
    :indicator: "##"
    :occurrences: "?"
    :fields:
    - - a
      - :occurrences: "?"
  "240":
    :master: "0"
    :indicator: "10"
    :occurrences: "?"
    :fields:
    - - a
      - :occurrences: "?"
    - - g
      - :occurrences: "?"
    - - h
      - :occurrences: "?"
    - - k
      - :occurrences: "?"
    - - m
      - :occurrences: "*"
    - - n
      - :occurrences: "*"
    - - o
      - :occurrences: "?"
    - - p
      - :occurrences: "?"
    - - r
      - :occurrences: "?"
  "250":
    :master: a
    :indicator: "##"
    :occurrences: "?"
    :fields:
    - - a
      - :occurrences: "?"
  "260":
    :master: a
    :indicator: "##"
    :occurrences: "+"
    :groupable: "8"
    :fields:
    - - a
      - :occurrences: "1"
    - - b
      - :occurrences: "1"
    - - c
      - :occurrences: "1"
    - - e
      - :occurrences: "?"
    - - f
      - :occurrences: "?"
    - - "8"
      - :occurrences: "?"
        :no_browse: true
  "264":
    :master: c
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - c
      - :occurrences: "?"
  "300":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :groupable: "8"
    :fields:
    - - a
      - :occurrences: "*"
    - - b
      - :occurrences: "?"
    - - c
      - :occurrences: "?"
    - - "8"
      - :occurrences: "?"
        :no_browse: true
  "337":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "500":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
        :browse_helper: application_helper_link_http
    - - "5"
      - :occurrences: "?"
        :no_browse: true
  "502":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "520":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "599":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "650":
    :master: "0"
    :indicator: ["00", "07"]
    :occurrences: "*"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: StandardTerm
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: term
    - - v
      - :occurrences: "*"
        :no_browse: true
    - - x
      - :occurrences: "*"
    - - y
      - :occurrences: "*"
        :no_browse: true
    - - z
      - :occurrences: "*"
        :no_browse: true
    - - "2"
      - :occurrences: "?"
        :no_browse: true
      # default "CH-BeSRO" value must be added during exportation
  "651":
    :master: "0"
    :indicator: "#7"
    :occurrences: "*"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Place
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: name
    - - "2"
      - :occurrences: "?"
        :no_browse: true
      # default "CH-BeSRO" value must be added during exportation
  "700":
    :master: "0"
    :indicator: "1#"
    :occurrences: "*"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Person
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: full_name
    - - d
      - :occurrences: "?"
        :browse_inline: true
        :foreign_class: ^0
        :foreign_field: life_dates
        :foreign_alternates: alternate_dates
        #:no_browse: true
    - - "e"
      - :occurrences: "*"
    - - "t"
      - :occurrences: "?"
    - - "4"
      - :occurrences: "*"
        :browse_inline: true
        #:no_browse: true
    - - "5"
      - :occurrences: "?"
        :no_browse: true
  "710":
    :master: "0"
    :indicator: "2#"
    :occurrences: "*"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Institution
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: name
    - - b
      - :occurrences: "*"
    - - k
      - :occurrences: "0"
        :export_as: "Source"
        :no_browse: true
    - - "e"
      - :occurrences: "*"
    - - "4"
      - :occurrences: "*"
    - - "5"
      - :occurrences: "?"
        :no_browse: true
  "730":
     :master: "a"
     :indicator: "0#"
     :occurrences: "*"
     :fields:
     - - a
       - :occurrences: "?"
  "760":
    :master: "0"
    :indicator: "2#"
    :occurrences: "*"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Publication
        :foreign_field: id
        :no_show: true
    - - t
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: title
    - - g
      - :occurrences: "*"
    - - o
      - :occurrences: "*"
        :no_browse: true
  "780":
    :master: "w"
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - "w"
      - :occurrences: "?"
        :foreign_class: Publication
        :foreign_field: id
        :no_show: true
    - - t
      - :occurrences: "?"
        :foreign_class: ^w
        :foreign_field: title
  "785":
    :master: "w"
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - "w"
      - :occurrences: "?"
        :foreign_class: Publication
        :foreign_field: id
        :no_show: true
    - - t
      - :occurrences: "?"
        :foreign_class: ^w
        :foreign_field: title
  "856":
    :master: u
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - u
      - :occurrences: "*"
        :browse_helper: application_helper_link_http
    - - z
      - :occurrences: "*"

