
# Version 2 - For SOLR and Muscat 3

config:
    :version: 2.0
    :model: work_node

fields:  
    "100a":
      :type: text
    "100d":
      :type: text 
    "100n":
      :type: text 
    "100n":
      :type: text 
    "100r":
      :type: text
    "100t":
      :type: text 
    "100p":
      :type: text 
    "100d_birthdate":
      :from_tag: "100"
      :from_subtag: "d"
      :index_helper: :marc_helper_get_birthdate
    "100d_deathdate":
      :from_tag: "100"
      :from_subtag: "d"
      :index_helper: :marc_helper_get_deathdate