config:
    :version: 2.0
    :model: inventory_item

fields:  
  "100a":
    :type: string
  "786i":
    :type: string
    :store: true
  "786o":
    :type: text
    :store: true
  "773w":
    :type: string
  "775w":
    :type: string
  "930w":
    :type: string
  "931w":
    :type: string
  "932w":
    :type: string

