--- !map:ActiveSupport::HashWithIndifferentAccess
_default_unknown_labels: true
main_work:
  label: gnd.main_work
variants:
  label: gnd.variants
references:
  label: gnd.references
codes:
  label: gnd.codes
relations:
  label: gnd.relations
control:
  label: gnd.control
unmatched:
  label: gnd.ungrouped
'001':
  label: gnd.rism_id_number
'003':
  label: gnd.control_number_identifier
'005':
  label: gnd.date_time_last_transaction
'024':
  fields:
    '2':
      label: gnd.source_number_code
    a:
      label: gnd.standard_number_code
  label: gnd.other_standard_identifier
'100':
  fields:
    a:
      label: gnd.name
    d:
      label: gnd.years_birth_death
    m:
      label: gnd.scoring_summary
    n:
      label: gnd.opus_thematic_index_number
    p:
      label: gnd.title_part
    r:
      label: gnd.key_or_mode
    t:
      label: gnd.title_of_work
  label: gnd.heading
'130':
  fields:
    a:
      label: gnd.work_title
    p:
      label: gnd.partial_title
  label: gnd.preferred_title
'382':
  fields:
    a:
      label: gnd.instrument
  label: gnd.instrument
'430':
  fields:
    a:
      label: gnd.work_title
    p:
      label: gnd.partial_title
  label: gnd.other_work_title
'548':
  fields:
    a:
      label: gnd.time
    i:
      label: gnd.reference_phrase
    w:
      label: gnd.control_subfield
    '4':
      label: gnd.relationship_code
    '9':
      label: gnd.remarks
  label: gnd.time_relationship
'550':
  fields:
    a:
      label: gnd.subject_term
    g:
      label: gnd.identifying_addition
    i:
      label: gnd.relationship_phase
    '0':
      label: gnd.record_idn
    '4':
      label: gnd.relationship_code
    '9':
      label: gnd.remarks
  label: gnd.subject_term_relationship
C+1:
  label: records.c_plus_1
C+2:
  label: records.c_plus_2
C+3:
  label: records.c_plus_3
C+4:
  label: records.c_plus_4
C+5:
  label: records.c_plus_5
C-1:
  label: records.c_minus_1
C-2:
  label: records.c_minus_2
C-3:
  label: records.c_minus_3
C-4:
  label: records.c_minus_4
C-5:
  label: records.c_minus_5
F+1:
  label: records.f_plus_1
F+2:
  label: records.f_plus_2
F+3:
  label: records.f_plus_3
F+4:
  label: records.f_plus_4
F+5:
  label: records.f_plus_5
F-1:
  label: records.f_minus_1
F-2:
  label: records.f_minus_2
F-3:
  label: records.f_minus_3
F-4:
  label: records.f_minus_4_bass
F-5:
  label: records.f_minus_5
G+1:
  label: records.g_plus_1
G+2:
  label: records.g_plus_2
G+3:
  label: records.g_plus_3
G+4:
  label: records.g_plus_4
G+5:
  label: records.g_plus_5
G-1:
  label: records.g_minus_1
G-2:
  label: records.g_minus_2_treble
G-3:
  label: records.g_minus_3
G-4:
  label: records.g_minus_4
G-5:
  label: records.g_minus_5
g-2:
  label: records.g_minus_2_octave