--- !map:Settings 
group_order: 
- edit_transcription
- edit_standardized_content
- edit_material_description
- edit_references
- edit_identifications
- edit_administration

groups: 
  edit_transcription: 
    all_tags: 
    - "773"
    - "245"
    - "246"
    - "031"

  edit_standardized_content:
    all_tags: 
    - "100"
    - '240'
    - '730'
    - '594'
    - '383'
    - "650"
    - '690'
    - '657'
    - '041'

  edit_material_description: 
    all_tags: 
    - '593'
    - '300'
  
  edit_references:
    all_tags:
    - '700' 
    - "710"
    - '691'
    - '500'

  edit_identifications:
    all_tags:
    - '786'
    - '930'
    - "931"
    - "932"
    - "933"
    - "787"

  edit_administration:
    all_tags:
    - '040'
    - '981'
    - '001'