--- !map:Settings
client:
  "024":
    tags:
      "2": required
      "a": required
  "100":
    tags:
      "a": 
        any_of:
          - mandatory
          - validate_person_name
      "d":
        any_of:
          - validate_calendar
          - validate_person_dates
  "400":
    tags:
      "a":
        any_of:
          - validate_person_name
          - required_if:
              "400": "j"
      "j":
        required_if:
          "400": "a"
  "500": 
    tags:
      "0":
        any_of:
          - required
          - not_record_id
      "i":
        required_if:
          "500": "0"
  "510": 
    tags:
      "0": required
  "551": 
    tags:
      "0": required
      "i":
        required_if:
          "551": "0"
  "670":
    tags:
      b:
        required_if:
          "670": "w"
      "u": validate_url
      "w": required
  "678":
    tags:
      "a": validate_calendar
  "856": 
    tags:
      u:
        any_of:
          - validate_url
          #- begins_with: "http"
          - required
      z:
        required_if:
          "856": "u"
      x:
        required_if:
          "856": "u"