--- !map:Settings 
"000": 
  tag: tag_no_subfield
  tag_params: 
    editor_only: true
  tag_header: none
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"003": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"005": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"020": 
  layout: 
    fields: 
    - - a
      - cols: 4
    columns: 4
"022": 
  layout: 
    fields: 
    - - a
      - cols: 4
    columns: 4
"041": 
  layout: 
    fields: 
    - - a
      - cols: 2 
        editor_partial: subfield_select_codes
        select_label: "Language"
    columns: 2
  tag_params:
    codes:
      - "alb"
      - "cat"
      - "cze"
      - "dan"
      - "dut"
      - "eng"
      - "est"
      - "fin"
      - "fre"
      - "frr"
      - "fry"
      - "ger"
      - "grc"
      - "gre" 
      - "gsw"
      - "heb"
      - "hrv"
      - "hun"
      - "ice"
      - "ita"
      - "jpn"
      - "kor"
      - "lat"
      - "lav"
      - "lit"
      - "nor"
      - "pol"
      - "por"
      - "rum"
      - "rus"
      - "slo"
      - "slv"
      - "spa"
      - "srp"
      - "swe"
      - "ukr"
      - "wen"
      - "zho"
      - "zxx"

"044": 
  layout: 
    fields: 
    - - a
      - cols: 2 
        editor_partial: subfield_select_codes
        select_label: "Country"
    columns: 2
  tag_params:
    codes:
      - "XC-DZ"
      - "XD-AR"
      - "XB-AM"
      - "XA-AD"
      - "XE-AU"
      - "XA-AT"
      - "XA-BE"
      - "XC-BJ"
      - "XD-BR"
      - "XA-BG"
      - "XB-KH"
      - "XD-CA"
      - "XD-CL"
      - "XB-CN"
      - "XD-CO"
      - "XA-HR"
      - "XD-CU"
      - "XA-CZ"
      - "XA-DK"
      - "XC-EG"
      - "XA-EE"
      - "XA-FI"
      - "XA-FR"
      - "XA-DE"
      - "XA-GR"
      - "XA-VA"
      - "XD-HN"
      - "XA-HU"
      - "XA-IS"
      - "XB-IN"
      - "XB-IR"
      - "XA-IE"
      - "XB-IL"
      - "XA-IT"
      - "XB-JP"
      - "XB-KR"
      - "XA-LV"
      - "XA-LT"
      - "XA-LU"
      - "XA-MT"
      - "XD-MX"
      - "XA-ME"
      - "XA-NL"
      - "XE-NZ"
      - "XA-NO"
      - "XD-PE"
      - "XD-PY"
      - "XA-PL"
      - "XA-PT"
      - "XD-PR"
      - "XA-RO"
      - "XA-RU"
      - "XA-RS"
      - "XA-SK"
      - "XA-SI"
      - "XC-ZA"
      - "XA-ES"
      - "XA-SE"
      - "XA-CH"
      - "XA-CH-VD"
      - "XB-SY"
      - "XD-TT"
      - "XB-TR"
      - "XA-UA"
      - "XA-GB"
      - "XD-US"
      - "XD-UY"
      - "XD-VE"
      - "XB-TW"
      - "XD-EC"
"100": 
  allow_new: true
  new_window: people
  layout: 
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
        allow_new: true
"210": 
  layout: 
    fields: 
    - - a
      - cols: 4
        trigger:
        - save:
          - referring_sources
    columns: 4
"240": 
  layout: 
    fields: 
    - - a
      - growfield: true
    - - g
      - cols: 1
        values:
        # http://www.loc.gov/standards/valuelist/marcgt.html
        - "Bibliography"
        - "Catalog"
        - "Catalog of works"
        - "Collective catalog"
        - "Encyclopedia"
        - "Music edition"
        - "Other"
        - "Thematic catalog"
        editor_partial: subfield_select
    - - h
      - cols: 1
        values:
        - "Article/chapter"
        - "Monograph"
        - "Periodical"
        - "Series"
        - "Volume in a series"
        - "Yearbook"
        editor_partial: subfield_select
"260": 
  layout: 
    fields: 
    - - a
      - cols: 4
    - - b
      - cols: 4
    - - c
      - cols: 4
    columns: 4
"264": 
  layout: 
    fields: 
    - - c
      - cols: 4
"300": 
  layout: 
    fields: 
    - - a
      - cols: 4
"337": 
  layout: 
    fields: 
    - - a
      - cols: 4
        values:
        - "CD-ROM"
        - "E-book"
        - "Electronic resource"
        - "Manuscript"
        - "Media combination"
        - "Microfiche"
        - "Microfilm"
        - "Printed medium"
        - "Printed music"
        default: "Printed medium"
        editor_partial: subfield_select
"500": 
  layout: 
    fields: 
    - - a
      - growfield: true
"520": 
  layout: 
    fields: 
    - - a
      - cols: 4
"599": 
  layout: 
    fields: 
    - - a
      - growfield: true
"650":
  allow_new: true
  new_window: standard_terms
  layout: 
    fields: 
    - - a
      - type: standard_term
        editor_partial: subfield_secondary
        allow_new: true
"651": 
  allow_new: true
  new_window: places
  layout: 
    fields: 
    - - a
      - type: place
        editor_partial: subfield_secondary
        allow_new: true
"700":
  allow_new: true
  new_window: people
  layout:
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
        allow_new: true
    - - "4"
      - editor_partial: subfield_select_codes
  tag_params: 
    codes: 
    - aut
    - edt
    - cmp
    - asn
    - oth
"710":
  new_window: institutions
  new_window_field: corporate_name_equals
  layout: 
    fields:
    - - a
      - type: institution
        editor_partial: subfield_secondary
        allow_new: true
    - - b
    - - c
      - type: place
        editor_partial: subfield_autocomplete
        autocomplete_extra: place
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
  tag_params: 
    codes: 
    - edt
    - oth
"760": 
  allow_new: true
  new_window: publications
  layout: 
    fields: 
    - - t
      - type: publication
        editor_partial: subfield_secondary
        allow_new: true
    - - g     

"780": 
  allow_new: true
  new_window: publications
  layout: 
    fields: 
    - - t
      - type: publication
        editor_partial: subfield_secondary
"785": 
  allow_new: true
  new_window: publications
  layout: 
    fields: 
    - - t
      - type: publication
        editor_partial: subfield_secondary
"856": 
  layout: 
    fields: 
    - - u
    - - z
