# A Place describes a physical place - like a city - where a Source is found
#
# === Fields
# * <tt>name</tt>
# * <tt>country</tt>
# * <tt>district</tt>
# * <tt>notes</tt>
# * <tt>src_count</tt>
#
# Usual wf_* fields are not shown

class Place < ApplicationRecord
  include ForeignLinks
  include CommentsCleanup
  include ThroughAssociations
  include AutoStripStrings
  include ComposedOfReimplementation
  include ThroughAssociations

  @last_user_save
  attr_accessor :last_user_save
  @last_event_save
  attr_accessor :last_event_save

  has_paper_trail :on => [:update, :destroy], :only => [:marc_source, :wf_stage, :wf_audit], :if => Proc.new { |t| VersionChecker.save_version?(t) }

  #has_and_belongs_to_many(:referring_sources, class_name: "Source", join_table: "sources_to_places")
  has_many :source_place_relations, class_name: "SourcePlaceRelation"
  has_many :referring_sources, through: :source_place_relations, source: :source

  #has_and_belongs_to_many(:referring_people, class_name: "Person", join_table: "people_to_places")
  has_many :person_place_relations, class_name: "PersonPlaceRelation"
  has_many :referring_people, through: :person_place_relations, source: :person

  #has_and_belongs_to_many(:referring_institutions, class_name: "Institution", join_table: "institutions_to_places")
  has_many :institution_place_relations, class_name: "InstitutionPlaceRelation"
  has_many :referring_institutions, through: :institution_place_relations, source: :institution
  
  #has_and_belongs_to_many(:referring_publications, class_name: "Publication", join_table: "publications_to_places")
  has_many :publication_place_relations, class_name: "PublicationPlaceRelation"
  has_many :referring_publications, through: :publication_place_relations, source: :publication

  #has_and_belongs_to_many(:referring_holdings, class_name: "Holding", join_table: "holdings_to_places")
  has_many :holding_place_relations, class_name: "HoldingPlaceRelation"
  has_many :referring_holdings, through: :holding_place_relations, source: :holding

  #has_and_belongs_to_many(:referring_works, class_name: "Work", join_table: "works_to_places")
  has_many :work_place_relations, class_name: "WorkPlaceRelation"
  has_many :referring_works, through: :work_place_relations, source: :work

  has_many :folder_items, as: :item, dependent: :destroy
  has_many :delayed_jobs, -> { where parent_type: "Place" }, class_name: 'Delayed::Backend::ActiveRecord::Job', foreign_key: "parent_id"
  belongs_to :user, :foreign_key => "wf_owner"

  composed_of_reimplementation :marc, :class_name => "MarcPlace", :mapping => %w(marc_source to_marc)


  #validates_presence_of :name
  #validates_uniqueness_of :name, scope: [:country, :district]

  #include NewIds

  before_destroy :check_dependencies, :cleanup_comments

  before_save :set_object_fields
  after_create :scaffold_marc, :fix_ids
  after_save :update_links, :reindex
  after_initialize :after_initialize

  attr_accessor :suppress_reindex_trigger
  attr_accessor :suppress_scaffold_marc_trigger
  attr_accessor :suppress_recreate_trigger
  attr_accessor :suppress_update_count_trigger

  alias_attribute :id_for_fulltext, :id

  enum :wf_stage, [ :inprogress, :published, :deleted, :deprecated ]
  enum :wf_audit, [ :basic, :minimal, :full ]

  def after_initialize
    @last_user_save = nil
    @last_event_save = "update"
  end

  # Suppresses the marc scaffolding
  def suppress_scaffold_marc
    self.suppress_scaffold_marc_trigger = true
  end
  
  def suppress_recreate
    self.suppress_recreate_trigger = true
  end 

  # Suppresses the solr reindex
  def suppress_reindex
    self.suppress_reindex_trigger = true
  end

  def suppress_update_count
    self.suppress_update_count_trigger = true
  end

  def reindex
    return if self.suppress_reindex_trigger == true
    self.index
  end

  def fix_ids
    #generate_new_id
    # If there is no marc, do not add the id
    return if marc_source == nil

    # The ID should always be sync'ed if it was not generated by the DB
    # If it was scaffolded it is already here
    # If we imported a MARC record into Person, it is already here
    # THis is basically only for when we have a new item from the editor
    marc_source_id = marc.get_marc_source_id
    if !marc_source_id or marc_source_id == "__TEMP__"

      self.marc.set_id self.id
      self.marc_source = self.marc.to_marc
      PaperTrail.request(enabled: false) do
        save
      end
    end
  end

  def update_links
    return if self.suppress_recreate_trigger == true

    allowed_relations = ["institutions", "people", "places", "publications"]
    ####recreate_links(marc, allowed_relations)
  end

  def scaffold_marc
    return if self.marc_source != nil  
    return if self.suppress_scaffold_marc_trigger == true
  
    new_marc = MarcPlace.new(File.read(ConfigFilePath.get_marc_editor_profile_path("#{Rails.root}/config/marc/#{RISM::MARC}/place/default.marc")))
    new_marc.load_source true
    
    new_marc.insert("151", a: self.name&.strip)
    new_marc.insert("370", c: self.country&.strip, f: self.district&.strip) if self.country || self.district
    new_marc.insert("667", a: self.notes&.strip) if self.notes && !self.notes.empty?
    
    self.alternate_terms&.split("\n")&.each do |term|
      new_marc.insert("451", a: term.strip)
    end

    if self.id != nil
      new_marc.set_id self.id
    end
    
    self.marc_source = new_marc.to_marc
    self.save!
  end

  searchable :auto_index => false do
    integer :id
    text :id_text do
      id_for_fulltext
    end
    string :name_order do
      name
    end
    text :name

    string :country_order do
      country
    end
    text :country

    text :notes
    text :alternate_terms

    string :district_order do
      district
    end
    text :district

    join(:folder_id, :target => FolderItem, :type => :integer, 
              :join => { :from => :item_id, :to => :id })
    
    integer(:src_count_order, :stored => true) {through_associations_source_count}
    integer(:referring_objects_order, stored: true) {through_associations_exclude_source_count}

  end

    def set_object_fields
    # This is called always after we tried to add MARC
    # if it was suppressed we do not update it as it
    # will be nil
    return if marc_source == nil
    
    # If the source id is present in the MARC field, set it into the
    # db record
    # if the record is NEW this has to be done after the record is created
    marc_source_id = marc.get_marc_source_id
    # If 001 is empty or new (__TEMP__) let the DB generate an id for us
    # this is done in create(), and we can read it from after_create callback
    self.id = marc_source_id if marc_source_id and marc_source_id != "__TEMP__"

    self.name = marc.get_place_name
    self.country = marc.get_place_country
    self.district = marc.get_place_district

    self.marc_source = self.marc.to_marc
  end

  def autocomplete_label
    [self.name&.strip, self.district&.strip, self.country&.strip].compact.reject(&:empty?).join(", ")
  end

  # https://github.com/activeadmin/activeadmin/issues/7809
  # In Non-marc models we can use the default
  def self.ransackable_associations(_) = reflections.keys
  def self.ransackable_attributes(_) = attribute_names - %w[token]
    
end

